name: CI

on:
  push:
    branches: [3.x, 4.x, 5.x]
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  testsuite:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
        prefer-lowest: ['']
        include:
          - php-version: '8.1'
            prefer-lowest: 'prefer-lowest'

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: pcov

      - name: Cache composer dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ matrix.prefer-lowest }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ matrix.prefer-lowest }}-

      - name: Composer install
        run: |
          if [[ "${{ matrix.prefer-lowest }}" == "prefer-lowest" ]]; then
            make install-dev-lowest
          elif [[ "${{ matrix.php-version }}" == "8.1" ]]; then
            make install-dev-ignore-reqs
          else
            make install-dev
          fi

      - name: Setup problem matchers for PHPUnit
        if: matrix.php-version == '8.1'
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run PHPUnit
        run: |
          if [[ "${{ matrix.php-version }}" == "8.1" && "${{ matrix.prefer-lowest }}" != "prefer-lowest" ]]; then
            export CODECOVERAGE=1
            vendor/bin/phpunit --display-incomplete --display-skipped --coverage-clover=coverage.xml
          else
            vendor/bin/phpunit
          fi

      - name: Submit code coverage
        if: matrix.php-version == '8.1' && matrix.prefer-lowest != 'prefer-lowest'
        uses: codecov/codecov-action@v5

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-8.1-${{ hashFiles('**/composer.lock') }}

      - name: Composer install
        run: make install-dev

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --report=checkstyle
